### ISSUE TITLE
Careers filter of department and location is not working

### ISSUE THREAD

**Issue by anthonydillon** [canonical/canonical.com#870] opened 2023-05-25 14:23 UTC
This link is not working correctly:
https://canonical.com/careers/all?filter=Web+%26+Design&location=americas

**Comment by LefterisXefteris** [comment] 2023-07-05 20:25
i Would love to fix this since the issue is not closed. could you specify what is wrong?

**Comment by carkod** [comment] 2023-07-25 14:11
I think the filter rmoved the location

**Comment by lathiat** [comment] 2024-01-02 02:09
Can we get this fixed? It's very difficult to search for APAC roles.

**Comment by carkod** [comment] 2024-01-05 10:02
Fixed by https://github.com/canonical/canonical.com/pull/1155

**Closed by carkod** 2024-01-05 10:02 UTC
Labels: Priority: High
