### ISSUE TITLE
Candidate Page shows 500: Server Error

### ISSUE THREAD

**Issue by apoorvamalhotra** [canonical/canonical.com#1257] opened 2024-05-22 18:03 UTC
*Note - filling in this form will file an issue against the canonical.com website*.
*Please provide as many details as possible in order to provide maintainers more context about the issue. Don't skip/remove any of the sections below. If there is no data to provide in one of the sections, please specify it by typing "N/A" or similar. That will help maintainers reproduce the issue and be able to help quickly. Thanks.*

## Summary

Candidate page shows 500: Server Error.
Issue was noticed post completion of the Psychometric assessment test.

## Steps to reproduce the behavior

1. Go to '[your candidate page](https://canonical.com/careers/application/gAAAAABmPF9Rl0y9pOiT_8ZjhHgN4-20mtkD4H__eWzvQbCjWXI_r_dKxC94hvvHZB6KWeSCL5CuF00UapFJNDiNB_HcsJa_vQ==) '

## Expected behavior

Candidate Page should open to track your progress in the recruitment process.

## Screenshot

<img width="1365" alt="Screenshot 2024-05-22 at 10 31 40 AM" src="https://github.com/canonical/canonical.com/assets/108534862/38c382fd-ba1f-4ec0-9142-16815b541709">

## Browser/device details

- Device: MacBook Air
- OS: macOS Sonoma Version 14.5
- Browser: Chrome
- Version: 125.0.6422.60

**Comment by lizzochek** [comment] 2024-06-17 10:05
Hello @apoorvamalhotra ! Thank you for filing an issue. If you were rejected or applied for another role, this may happen. Did any of the mentioned happen? If no, could you provide more context?

**Comment by lizzochek** [comment] 2024-06-25 12:22
Hello @apoorvamalhotra ! thank you for filing an issue. The issue happened, because this application was a duplicate of another one, therefore applications got merged and this one does not exist anymore. 
Here's the new application:
https://canonical.com/careers/application/gAAAAABmSQzBimNXgNc0mvbOquL4M0TR4rErvBnz2PLffDr1_fhVYjOf8owBNBsCl2E4yLRrqoVVFgnpwAM3Msr805gUBQ1Sng==
It shows 404, because you (very unfortunately :( ) were rejected. Please let us know if you need further support.

**Comment by lizzochek** [comment] 2024-06-25 12:23
Hello @apoorvamalhotra ! thank you for filing an issue. The issue happened, because this application was a duplicate of another one, therefore applications got merged and this one does not exist anymore. 
Here's the new application:
https://canonical.com/careers/application/gAAAAABmSQzBimNXgNc0mvbOquL4M0TR4rErvBnz2PLffDr1_fhVYjOf8owBNBsCl2E4yLRrqoVVFgnpwAM3Msr805gUBQ1Sng==
It shows 404, because you (very unfortunately 😢) were rejected. Please let us know if you need further support.

**Closed by lizzochek** 2024-06-25 12:23 UTC
