### ISSUE TITLE
canonical.com/careers search does not match role location (e.g.: apac, worldwide)

### ISSUE THREAD

**Issue by lathiat** [canonical/canonical.com#817] opened 2023-03-17 05:25 UTC
## Summary

When searching jobs using the "Search by keyword" box on canonical.com/careers, the search does not match the job location text listed in the auto-complete results.

As a minimum fix, I would expect the search to match any word appearing in the auto-completed results list. Having words appear in the results list that do not match the search is particularly confusing. It's additionally confusing because a few jobs have APAC or a country name in the job title so do match - giving you at least some results which may mislead you into incorreclty thinking there are no more.

There is greater scope to better handle location search in general in multiple ways (e.g. this simple fix means searching "apac" here wouldn't match a worldwide job), but I will open that as a separate bug, and I still think this specific issue is worth fixing despite that.

## Process

1. Visit https://canonical.com/careers
3. Using the "Search by keyword" box at the top, search for a role title which has a "Home based - APAC" position listed, but do not submit the form (At the time of writing that includes "Field Software Engineer" or "Engineering Manager")
4. Observe the auto-complete list includes the matching position title but also the location words "Home based - APAC"
5. Clear the box and now search for APAC, again not submitting the form
6. Observe that the results, at the time of writing, include two roles which have APAC in the job title (Cloud Operations Engineer, APAC; Site Reliability Engineer, APAC) but does not include "Field Software Engineer - India" or any other role which shows that location text.
7. Additionally you can observe that a search for "Worldwide" has no results.

The same results are seen if you submit the form, however, since you can drive this entire page by using the autocomplete and then clicking on the resulting autocomplete entry (which takes you directly to the job listing with no search context), I think this method of use is more confusing. Particularly as the submitted search page includes a location option but that does not appear on the main page when using autocomplete results.

## Current and expected result

Current result: The keyword search does not match every word shown in the autocomplete search results, specifically, it does not currently match the location
Expected result: The keyword search should match every word shown in the autocomplete search results, as a minimnum

## Screenshot

![image](https://user-images.githubusercontent.com/290673/225819476-51beb531-f0f8-4066-85be-327d1a502ee5.png)

## Browser details

Chrome 111.0.5563.64 (Official Buidl) (arm64) - MacOS Ventura 13.2.1

**Comment by marinacastejon** [comment] 2023-03-23 10:49
Hi @lathiat I agree with you, this would be an improvement on the user experience. Thanks for raising it. I have created an internal issue in this [JIRA issue](https://warthogs.atlassian.net/browse/WD-2814).

**Comment by chrisschnabel** [comment] 2023-10-23 16:00
@marinacastejon I was about to open an issue, but the behavior I observe seems to be the potential root cause of this issue.

When you filter on canonical.com/careers, it does an OR of all available filters even though some of those filters are by region and others are by department. The behavior I would expect is:

(OR of all department filters) AND (OR of all region filters)

So, if I filter by 'Legal', and 'Product, and EMEA; I should see all legal or product roles in EMEA.  Today, this instead behaves by giving me all product roles, all legal roles, and all roles in EMEA (including e.g. support engineering).

Here is the example with just 'Legal' and 'Product' selected:

![image](https://github.com/canonical/canonical.com/assets/17765851/a3febb6b-b409-4963-becc-578bc4f6232e)

and if I add the EMEA filter you can see the number goes up and not down:

![image](https://github.com/canonical/canonical.com/assets/17765851/38a2f35a-709a-4348-8bf4-8af047f5715d)

**Comment by juanruitina** [comment] 2024-01-03 11:57
Fixed by https://github.com/canonical/canonical.com/pull/1150

**Closed by juanruitina** 2024-01-03 11:57 UTC
