### ISSUE TITLE
Candidate Page : 401  Unauthorized You do not have access to this page.

### ISSUE THREAD

**Issue by abdulwaheed-apk** [canonical/canonical.com#1335] opened 2024-08-08 10:50 UTC
## Summary

On the candidate page, it appears that 401 Unauthorized, and you do not have access error.
 
## Steps to reproduce the behavior

1. Go to [canonical.com](https://canonical.com/)
2. If you have an ongoing application, go to the candidate page and see the error.

Note: I have the URL of my application page, and I'm not sure if I should provide that here.

## Expected behavior

Here, you should be able to track your progress through Canonical's interview stages, learn about your Hiring Lead, and watch a video about the hiring process.

## Screenshot

[Brave]

![Canonical](https://github.com/user-attachments/assets/bd5588ff-9a03-4f4c-adae-dd75528ee35e)

[Firefox]

![Canonical firefox](https://github.com/user-attachments/assets/672e7532-bcca-4f89-856f-a64fbd68235c)

## Browser/device details

- Device: Dell Latitude 3520
- OS: Windows 11 Home 23H2
- Browser Firefox, Brave
- Version Firefox 129.0 (64-bit), Brave V 1.68.137(Chromium 127)

**Comment by motoraif** [comment] 2024-08-12 13:14
I have faced the same error.

**Comment by mtruj013** [comment] 2024-08-28 08:17
Hi all, this is a duplicate of https://github.com/canonical/canonical.com/issues/1354, please follow the latest updates there

**Closed by mtruj013** 2024-08-28 08:17 UTC
