### ISSUE TITLE
Candidate page fails with 500 error code

### ISSUE THREAD

**Issue by saz01** [canonical/canonical.com#1025] opened 2023-08-25 19:18 UTC
![image](https://github.com/canonical/canonical.com/assets/44998322/e57f8c36-60a3-4ee1-9daf-df8003629ba1)

**Comment by anthonydillon** [comment] 2023-08-25 22:17
Thanks for reporting this issue. Can you try to refresh the page. I believed we got a short API outage.

**Comment by saz01** [comment] 2023-08-26 00:51
Am still getting the same error.

**Comment by Panos90** [comment] 2023-08-28 11:12
Hey folks, I can confirm I am experiencing the same error.

**Comment by anthonydillon** [comment] 2023-08-29 21:47
I believe this issue has now been rectified @mtruj013?

**Comment by mtruj013** [comment] 2023-08-30 08:25
@anthonydillon this looks like a different error than the form submission one. Will investigate

**Comment by anthonydillon** [comment] 2023-08-30 08:33
I have checked and the application page seems to be working for @Panos90. Could you confirm please?

**Comment by mtruj013** [comment] 2023-08-30 10:24
I am still getting 500, but I'm not sure if it's because of the test token I'm using. @saz01 @Panos90 are you all able to access your candidate page successfully?

**Comment by mtruj013** [comment] 2023-08-30 12:11
Update: it was definitely my token, I've gotten a new one and cannot replicate this issue. Will wait until the reporters answer before closing cc: @anthonydillon

**Comment by Panos90** [comment] 2023-08-30 14:07
Hey folks, I can access my candidate page but I am still getting a 500: Server Error when trying to withdraw my application.

**Comment by saz01** [comment] 2023-08-31 05:57
@mtruj013 Am still facing the issue. 
![canonical](https://github.com/canonical/canonical.com/assets/44998322/28e9b6cc-60d3-4bb8-bad9-97c2092bd7ff)

**Comment by mtruj013** [comment] 2023-09-04 08:03
@Panos90 @saz01 could you share what OS and browser you're using? I've not been able to recreate the withdrawal error. @saz01 are you still getting a 500 when you try to access your application page or are you also trying to withdraw your application?

**Comment by TiberiuFarcasAdrian** [comment] 2023-09-07 18:49
![image](https://github.com/canonical/canonical.com/assets/116016612/2b3155a8-f8c3-4b01-8340-ca66b6668b2c)
I am also getting this error. I am using Google Chrome on a Windows 10 OS.

**Comment by samhotep** [comment] 2023-09-08 13:40
@saz01 @TiberiuFarcasAdrian please try again, it should be working now

**Comment by TiberiuFarcasAdrian** [comment] 2023-09-08 13:51
@samhotep Yes, it worked.

**Comment by Panos90** [comment] 2023-09-08 15:17
It worked for me folks (Brave browser , MacOS), thanks.

**Comment by kevinlambert** [comment] 2023-10-09 09:14
I'm getting a 500 on the following url https://canonical.com/careers/4453144/application

**Comment by akbarkz** [comment] 2023-10-13 04:25
@saz01 @kevinlambert guys, can you try again? are you still getting 500?

**Comment by LeaDevelop** [comment] 2023-10-22 23:57
> I'm getting a 500 on the following url https://canonical.com/careers/4453144/application

this page loads for me 👍🏻

**Comment by gatezh** [comment] 2023-10-30 21:21
Same here: 500 Server error
macOS 13.6.1, Safari 17.1

**Comment by legoadk** [comment] 2023-10-30 21:44
I can confirm that after filling all the fields in an application (https://canonical.com/careers/2456563) and clicking "submit", a 500 Internal Server Error is presented.
This also happens if you happened to browse away from the page (for example, if you clicked on the Recruitment Privacy Notice to review it as suggested) and then browsing "back" to application with your browser.
(those links should really be target="_blank" so they open in new windows/tabs).

**Comment by afreet** [comment] 2023-11-29 17:18
I am also getting a 500 error when accessing the [Candidate Page](https://canonical.com/careers/application/gAAAAABlZQ0zoBxGWVHKklNCv82tM5Id0oOji4mJTBiD6_YpdIYJCysdaZIG77AovrVQL65EE1UKyJCJ-VLfY5XRwqFVQhtabw==) link provided to me via email

**Comment by anthonydillon** [comment] 2023-11-29 21:30
Thanks, we have a new issue which we are working on at the moment.

**Comment by afreet** [comment] 2023-12-06 00:43
I just loaded up the page successfully today. Thanks!

**Closed** 2023-12-14 18:19 UTC
Labels: Priority: Critical
